name: Cekips International
title: Cekips International
description: Online Business Directory
logo: assets/images/idnlogos.png
favicon: assets/images/techico.png
baseurl: ''
google_analytics: 'UA-209667013-4'
include:
  - _pages
permalink: '/:title/'
authors:
  techidn:
    name: Cekips
    display_name: Cekips
    email: krvsuite@gmail.com
    twitter: ''
    description: "Keep up with us for the inside scoop on where to find the best spots in town!."
    web: "https://cekips.com"
    gravatar: 0397aa39d5259d69961beaf1155fa085
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
paginate: 6
paginate_path: '/page:num/'
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true
adsense: 'disabled'
adsense-data-ad-client: 'ca-pub-9071991042477013'
adsense-data-ad-slot: '7908225664'
lazyimages: 'enabled'
exclude:
  - changelog.md
  - LICENSE.txt
  - README.md
  - Gemfile
  - Gemfile.lock
jekyll_admin:
  hidden_links:
    - datafiles
